ktor:
  application:
    modules:
      - com.benjiiross.coachandco.ApplicationKt.module
  deployment:
    port: 8080

database:
  driver:
  url:
  username:
  password:
  maximumPoolSize:
  minimumIdle:
  idleTimeout:
  connectionTimeout:
  maxLifetime:

jwt:
  secret:
  domain:
  audience:

isDevelopment: true